version: 2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install cookiecutter
          name: Install Cookiecutter
      - run:
          name: Create project test from cookiecutter
          command: cookiecutter . --no-input
      - run:
          name: Run the tests
          command: |
            cd my-flask-app
            make run-tests

workflows:
  main:
    jobs:
      - build-and-test
