version: 2.1
orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: pipenv pip install cookiecutter
          name: Install Cookiecutter
      - run:
          name: Create project test from cookiecutter
          command: pipenv cookiecutter . --no-input
      - run:
          name: Install requirements from cookiecutter
          command: |
            cd my-flask-app
            pipenv make requirements
      - run:
          name: Run the tests
          command: |
            cd my-flask-app
            pipenv make run-tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  main:
    jobs:
      - build-and-test
